services:
  api:
    build:
      context: ./backend
      dockerfile: ../docker/go/Dockerfile.dev
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - ./backend:/go/src/app
    env_file: backend/.env
    tty: true
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Tokyo
    env_file: backend/.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data