/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 認証ユーザー取得
     * @description Bearer トークンから認証済みユーザーの情報を取得する
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['MeResponse']
          }
        }
        401: components['responses']['UnauthorizedError']
        500: components['responses']['InternalServerError']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    MeResponse: {
      /**
       * Format: uuid
       * @description ユーザーID
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string
      /**
       * @description ユーザー名
       * @example 田中太郎
       */
      name: string
      /**
       * Format: email
       * @description メールアドレス
       * @example tanaka@example.com
       */
      email: string
    }
    ErrorResponse: {
      /** @description エラーコード */
      code: string
      /** @description エラーメッセージ */
      message: string
    }
  }
  responses: {
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "code": "unauthorized",
         *       "message": "認証が必要です"
         *     }
         */
        'application/json': components['schemas']['ErrorResponse']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "code": "internal_server_error",
         *       "message": "予期しないエラーが発生しました"
         *     }
         */
        'application/json': components['schemas']['ErrorResponse']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
