// Code generated by MockGen. DO NOT EDIT.
// Source: get_joined_groups.go
//
// Generated by this command:
//
//	mockgen -source=get_joined_groups.go -destination=../test/mock/usecase/get_joined_groups_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	usecase "backend/usecase"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetJoinedGroups is a mock of GetJoinedGroups interface.
type MockGetJoinedGroups struct {
	ctrl     *gomock.Controller
	recorder *MockGetJoinedGroupsMockRecorder
	isgomock struct{}
}

// MockGetJoinedGroupsMockRecorder is the mock recorder for MockGetJoinedGroups.
type MockGetJoinedGroupsMockRecorder struct {
	mock *MockGetJoinedGroups
}

// NewMockGetJoinedGroups creates a new mock instance.
func NewMockGetJoinedGroups(ctrl *gomock.Controller) *MockGetJoinedGroups {
	mock := &MockGetJoinedGroups{ctrl: ctrl}
	mock.recorder = &MockGetJoinedGroupsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetJoinedGroups) EXPECT() *MockGetJoinedGroupsMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetJoinedGroups) Execute(ctx context.Context, userID string) ([]usecase.GetJoinedGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].([]usecase.GetJoinedGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetJoinedGroupsMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetJoinedGroups)(nil).Execute), ctx, userID)
}
