// Code generated by MockGen. DO NOT EDIT.
// Source: get_group.go
//
// Generated by this command:
//
//	mockgen -source=get_group.go -destination=../test/mock/usecase/get_group_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	usecase "backend/usecase"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetGroup is a mock of GetGroup interface.
type MockGetGroup struct {
	ctrl     *gomock.Controller
	recorder *MockGetGroupMockRecorder
	isgomock struct{}
}

// MockGetGroupMockRecorder is the mock recorder for MockGetGroup.
type MockGetGroupMockRecorder struct {
	mock *MockGetGroup
}

// NewMockGetGroup creates a new mock instance.
func NewMockGetGroup(ctrl *gomock.Controller) *MockGetGroup {
	mock := &MockGetGroup{ctrl: ctrl}
	mock.recorder = &MockGetGroupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGroup) EXPECT() *MockGetGroupMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetGroup) Execute(ctx context.Context, in usecase.GetGroupInput) (usecase.GetGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(usecase.GetGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetGroupMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetGroup)(nil).Execute), ctx, in)
}
