// Code generated by MockGen. DO NOT EDIT.
// Source: group_invitation.go
//
// Generated by this command:
//
//	mockgen -source=group_invitation.go -destination=../test/mock/usecase/group_invitation_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	usecase "backend/usecase"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGroupInvitation is a mock of GroupInvitation interface.
type MockGroupInvitation struct {
	ctrl     *gomock.Controller
	recorder *MockGroupInvitationMockRecorder
	isgomock struct{}
}

// MockGroupInvitationMockRecorder is the mock recorder for MockGroupInvitation.
type MockGroupInvitationMockRecorder struct {
	mock *MockGroupInvitation
}

// NewMockGroupInvitation creates a new mock instance.
func NewMockGroupInvitation(ctrl *gomock.Controller) *MockGroupInvitation {
	mock := &MockGroupInvitation{ctrl: ctrl}
	mock.recorder = &MockGroupInvitationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupInvitation) EXPECT() *MockGroupInvitationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGroupInvitation) Execute(ctx context.Context, input usecase.GroupInvitationInput) (usecase.GroupInvitationOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(usecase.GroupInvitationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGroupInvitationMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGroupInvitation)(nil).Execute), ctx, input)
}
