// Code generated by MockGen. DO NOT EDIT.
// Source: signup.go
//
// Generated by this command:
//
//	mockgen -source=signup.go -destination=../test/mock/usecase/signup_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	usecase "backend/usecase"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignUp is a mock of SignUp interface.
type MockSignUp struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpMockRecorder
	isgomock struct{}
}

// MockSignUpMockRecorder is the mock recorder for MockSignUp.
type MockSignUpMockRecorder struct {
	mock *MockSignUp
}

// NewMockSignUp creates a new mock instance.
func NewMockSignUp(ctrl *gomock.Controller) *MockSignUp {
	mock := &MockSignUp{ctrl: ctrl}
	mock.recorder = &MockSignUpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUp) EXPECT() *MockSignUpMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSignUp) Execute(ctx context.Context, in usecase.SignUpInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSignUpMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSignUp)(nil).Execute), ctx, in)
}
