openapi: 3.0.0
info:
  title: Share Basket API
  description: API for Share Basket application
  version: 1.0.0
servers:
  - url: /api
    description: API server
paths:
  /signup:
    post:
      summary: ユーザー登録
      description: 新規ユーザーを作成します
      operationId: signUp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '204':
          description: ユーザー登録成功
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /signup/confirm:
    post:
      summary: ユーザー登録確認
      description: 確認コードを使用してユーザー登録を完了します
      operationId: signUpConfirm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpConfirmRequest'
      responses:
        '204':
          description: ユーザー登録確認成功
        '400':
          $ref: '#/components/responses/BadRequest'
        '410':
          $ref: '#/components/responses/ExpiredCode'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /login:
    post:
      summary: ログイン
      description: メールアドレスとパスワードでログインします
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '204':
          description: ログイン成功
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /reset-password:
    post:
      summary: パスワードリセット
      description: パスワードリセット用のメールを送信します
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '204':
          description: パスワードリセットメール送信成功
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /reset-password/confirm:
    post:
      summary: パスワードリセット確認
      description: 確認コードを使用してパスワードリセットを確認します
      operationId: resetPasswordConfirm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordConfirmRequest'
      responses:
        '204':
          description: パスワードリセット確認成功
        '400':
          $ref: '#/components/responses/BadRequest'
        '410':
          $ref: '#/components/responses/ExpiredCode'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /signup/resend-code:
    post:
      summary: 確認コード再送信
      description: 会員登録時に使用する確認コードを再送信します
      operationId: resendConfirmationCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationCodeRequest'
      responses:
        '204':
          description: 確認コード再送信成功
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    BadRequest:
      description: リクエスト不正
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 'BAD_REQUEST'
            message: 'リクエストが不正です'
    ExpiredCode:
      description: 確認コードの有効期限切れ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 'EXPIRED_CODE'
            message: '確認コードの有効期限が切れています'
    Unauthorized:
      description: 認証エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 'UNAUTHORIZED'
            message: 'メールアドレスまたはパスワードが正しくありません'
    InternalServerError:
      description: サーバーエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 'INTERNAL_SERVER_ERROR'
            message: 'サーバーエラーが発生しました'

  schemas:
    SignUpRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          description: ユーザー名
        email:
          type: string
          format: email
          description: メールアドレス
        password:
          type: string
          format: password
          description: パスワード
    SignUpConfirmRequest:
      type: object
      required:
        - email
        - confirmationCode
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
        confirmationCode:
          type: string
          description: 確認コード
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
        password:
          type: string
          format: password
          description: パスワード
    ResetPasswordRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
    ResetPasswordConfirmRequest:
      type: object
      required:
        - email
        - confirmationCode
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
        confirmationCode:
          type: string
          description: 確認コード
    ResendConfirmationCodeRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          description: メールアドレス
    Error:
      type: object
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ 