name: Backend Test

on:
  push:
    branches:
      - main
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

env:
  TEST_DB_HOST: 127.0.0.1
  TEST_DB_PORT: 5432
  TEST_DB_NAME: kaimon_test
  TEST_DB_USER: kaimon
  TEST_DB_PASSWORD: password

defaults:
  run:
    working-directory: backend

jobs:
  test:
    name: Run golang test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.TEST_DB_NAME }}
          POSTGRES_USER: ${{ env.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.TEST_DB_PASSWORD }}
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.mod
          cache-dependency-path: ./backend/go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go mod download
      - name: Run test
        run: go test ./...